backend:
  name: github
  repo: piotrkossa/IhaniClubWebsite
  branch: netlify
  base_url: "https://ihani.pages.dev"
  auth_endpoint: "/.netlify/functions/auth"

media_folder: "docs/static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "announcements"
    label: "Ogłoszenia"
    folder: "docs/content/announcements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Treść", name: "body", widget: "text" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Zdjęcie", name: "image", widget: "image", required: false }
