name: Publish Dev Branch to /dev safely

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev
          path: dev-repo

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-repo

      - name: Clean & copy dev files
        run: |
          rm -rf main-repo/docs/dev
          mkdir -p main-repo/docs/dev
          rsync -av --exclude='.git' dev-repo/ main-repo/docs/dev/

      - name: Commit & push
        run: |
          cd main-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/dev
          git commit -m "Update /dev from dev branch [skip ci]" || echo "No changes to commit"
          git push origin main
