name: Publish Dev Branch to /dev safely

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          path: dev-repo

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean & copy dev files
        run: |
          rm -rf main-repo/docs/dev
          mkdir -p main-repo/docs/dev
          rsync -av --exclude='.git' dev-repo/ main-repo/docs/dev/

      - name: Commit & push
        run: |
          cd main-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/dev
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update /dev from dev branch [skip ci]"
            git push
          fi
